version: '3.9'

services:
  # Serviço para a aplicação Spring Boot
  user-api:
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    container_name: user-api-java
    ports:
      - "8080:8080"  # Expõe a porta 8080 do container para a máquina local
    environment:
      # A URL aponta para 'mysql-db' em vez de 'localhost'
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/usuarios_api?useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: senha_db
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_SHOW-SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      
      # Variável de segurança JWT
      API_SECURITY_TOKEN_SECRET: ${JWT_SECRET:-SUA_CHAVE_AQUI}

      # Site bara gerar chave JWT: https://packtypebot.com.br/gerador/jwt.php

    depends_on:
      - mysql-db
    networks:
      - userapi-network

  # Serviço para o MySQL
  mysql-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: senha_db  # Senha do root do MySQL
      MYSQL_DATABASE: usuarios_api  # Nome do banco de dados a ser criado
    ports:
      - "3303:3306"  # Expor a porta [(host->container)(3303->3306)] para conectar localmente
    volumes:
      - mysql-data:/var/lib/mysql  # Persistir os dados do banco de dados
    networks:
      - userapi-network

networks:
  userapi-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
